//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTypes
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public decimal DailyCost { get; set; }
        public decimal DailyLateCost { get; set; }
        public string Gear { get; set; }
    }
}
