//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public System.DateTime LeaseStartDate { get; set; }
        public System.DateTime LeaseEndDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
        public int CustomerId { get; set; }
        public int CarId { get; set; }
    }
}
